version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
  kafka:
    image: wurstmeister/kafka
    links:
    - "zookeeper:zk"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE : "false"
      KAFKA_CREATE_TOPICS: "test-counts:1:1,aggregate-counts:1:1"
    volumes:
    - ./scripts:/scripts
    - /var/run/docker.sock:/var/run/docker.sock